# Generated by Django 3.2.9 on 2021-11-30 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0003_auto_20211129_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='hospital',
        ),
        migrations.AddField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memorial',
            name='cvm_status',
            field=models.CharField(default='New', max_length=200),
        ),
        migrations.AlterField(
            model_name='memorial',
            name='memorial_status',
            field=models.CharField(default='New', max_length=200),
        ),
        migrations.AlterField(
            model_name='memorial',
            name='payment_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='memorial',
            name='payment_status',
            field=models.CharField(default='Not Paid', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='memorials.hospital'),
        ),
    ]
