# Generated by Django 3.2.9 on 2021-11-30 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0006_donation_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='memorial',
        ),
        migrations.AddField(
            model_name='memorial',
            name='donation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='memorials.donation'),
        ),
    ]
