# Generated by Django 3.2.9 on 2021-11-30 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0007_auto_20211130_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorial',
            name='donation',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='memorials.donation'),
        ),
    ]
