# Generated by Django 3.2.9 on 2021-11-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0008_alter_memorial_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorial',
            name='payment_code',
        ),
        migrations.RemoveField(
            model_name='memorial',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='memorial',
            name='submitted_for_payment_date',
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_status',
            field=models.CharField(default='Not Paid', max_length=200),
        ),
        migrations.AddField(
            model_name='donation',
            name='submitted_for_payment_date',
            field=models.DateField(null=True),
        ),
    ]
