# Generated by Django 3.2.9 on 2021-11-30 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0009_auto_20211130_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorial',
            name='donation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='memorials.donation'),
        ),
    ]
