# Generated by Django 3.2.9 on 2021-11-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0010_alter_memorial_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='count_mems_submitted',
            field=models.IntegerField(default=0),
        ),
    ]
