# Generated by Django 3.2.9 on 2021-12-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0012_auto_20211201_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorial',
            name='pet_gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=10),
        ),
    ]
