# Generated by Django 3.2.9 on 2021-12-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0013_alter_memorial_pet_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='fund_description',
            field=models.TextField(),
        ),
    ]
