# Generated by Django 3.2.9 on 2021-12-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0014_alter_fund_fund_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='hosp_add_one',
            new_name='address_one',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='hosp_add_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='hosp_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='hosp_add_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='hosp_add_state',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='memorial',
            name='pet_gender',
        ),
        migrations.AddField(
            model_name='memorial',
            name='bad_address',
            field=models.BooleanField(default=False),
        ),
    ]
