# Generated by Django 3.2.9 on 2021-12-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0015_auto_20211208_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='donation_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='donation_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='donation_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='donation_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='fund_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='fund_url_code',
            new_name='url_code',
        ),
        migrations.RenameField(
            model_name='memorial',
            old_name='memorial_create_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='memorial',
            old_name='memorial_status',
            new_name='status',
        ),
        migrations.AddField(
            model_name='hospital',
            name='billing_address_one',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='hospital',
            name='billing_address_state',
            field=models.CharField(default='GA', max_length=2),
        ),
        migrations.AddField(
            model_name='hospital',
            name='billing_address_two',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='billing_address_zipcode',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='hospital',
            name='billing_contact_email',
            field=models.EmailField(default='smithe@gmail.com', max_length=200),
        ),
        migrations.AddField(
            model_name='hospital',
            name='billing_name',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='hospital',
            name='billing_phone_number',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='primary_hospital_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='state',
            field=models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DC', 'Washington D.C.'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='GA', max_length=2),
        ),
    ]
